services:
  db:
    image: postgres:15-alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: KI_ITK
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: ki-backend
    working_dir: /app
    # volumes:
    #   - ./:/app

    environment:
      - PORT=9000
      - DB_USERNAME=postgres
      - DB_PASSWORD=root
      - DB_NAME=KI_ITK
      - DB_HOST=db
      - DB_PORT=5432
      - JWT_SECRET=secret
      - SALT_ROUNDS=12
      - BASE_URL=http://localhost:5173
      - EMAIL_USER=nuralirajab03@gmail.com
      - EMAIL_PASS=bczysvhnbebssvea
      - MAIL_FROM_NAME=KI-ITK
      - NODE_ENV=production
    ports:
      - "9000:9000"
    depends_on:
      - db
    networks:
      - app-network

  nginx:
    image: nginx:1.25-alpine
    container_name: nginx-ki
    restart: always
    ports:
      - "8032:80"
      - "8033:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
