services:
  db:
    image: postgres:15-alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: KI_ITK
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: ki-backend
    working_dir: /app
    volumes:
      - ./:/app

    environment:
      - PORT=9000
      - DB_USERNAME=postgres
      - DB_PASSWORD=root
      - DB_NAME=KI_ITK
      - DB_HOST=db
      - DB_PORT=5432
      - JWT_SECRET=secret
      - SALT_ROUNDS=12
      - BASE_URL=http://localhost:5173
      - EMAIL_USER=nuralirajab03@gmail.com
      - EMAIL_PASS=bczysvhnbebssvea
      - MAIL_FROM_NAME=KI-ITK
      - NODE_ENV=production
      - VIRTUAL_HOST=api-hki.wynz.site,www.api-hki.wynz.site
      - VIRTUAL_PORT=9000
      - LETSENCRYPT_HOST=api-hki.wynz.site,www.api-hki.wynz.site
      - LETSENCRYPT_EMAIL=septianushendra3@gmail.com

    depends_on:
      - db
    networks:
      - app-network
      - proxy-network
volumes:
  postgres_data:

networks:
  app-network:
  proxy-network:
    external: true
